"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-07-20 02:12:09.786818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agenda_template'))
    )
    op.create_table('join_form_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('fields_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_join_form_template'))
    )
    op.create_table('agenda_template_milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['agenda_template.id'], name=op.f('fk_agenda_template_milestone_template_id_agenda_template'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agenda_template_milestone'))
    )
    with op.batch_alter_table('agenda_template_milestone', schema=None) as batch_op:
        batch_op.create_index('ix_agenda_template_milestone_template_position', ['template_id', 'position'], unique=False)

    op.create_table('workshop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=False),
    sa.Column('admin_token', sa.String(length=64), nullable=False),
    sa.Column('join_slug', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_hours', sa.Integer(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('content_version', sa.Integer(), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('join_form_json', sa.Text(), nullable=False),
    sa.Column('stuck_minutes', sa.Integer(), nullable=False),
    sa.Column('cloned_from_id', sa.Integer(), nullable=True),
    sa.Column('agenda_template_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agenda_template_id'], ['agenda_template.id'], name=op.f('fk_workshop_agenda_template_id_agenda_template'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cloned_from_id'], ['workshop.id'], name=op.f('fk_workshop_cloned_from_id_workshop')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshop'))
    )
    with op.batch_alter_table('workshop', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workshop_admin_token'), ['admin_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_workshop_agenda_template_id'), ['agenda_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workshop_cloned_from_id'), ['cloned_from_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workshop_join_slug'), ['join_slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_workshop_status'), ['status'], unique=False)

    op.create_table('broadcast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('message_md', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.id'], name=op.f('fk_broadcast_workshop_id_workshop'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcast'))
    )
    with op.batch_alter_table('broadcast', schema=None) as batch_op:
        batch_op.create_index('ix_broadcast_workshop_cleared', ['workshop_id', 'cleared_at'], unique=False)

    op.create_table('facilitator_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=False),
    sa.Column('undo_data_json', sa.Text(), nullable=True),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.id'], name=op.f('fk_facilitator_action_workshop_id_workshop'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilitator_action'))
    )
    with op.batch_alter_table('facilitator_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facilitator_action_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_facilitator_action_workshop_created', ['workshop_id', 'created_at'], unique=False)

    op.create_table('milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.id'], name=op.f('fk_milestone_workshop_id_workshop'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestone'))
    )
    with op.batch_alter_table('milestone', schema=None) as batch_op:
        batch_op.create_index('ix_milestone_workshop_id_position', ['workshop_id', 'position'], unique=False)

    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.id'], name=op.f('fk_participant_workshop_id_workshop'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant'))
    )
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participant_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_participant_workshop_id'), ['workshop_id'], unique=False)

    op.create_table('help_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('ai_state', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], name=op.f('fk_help_request_milestone_id_milestone'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_help_request_participant_id_participant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.id'], name=op.f('fk_help_request_workshop_id_workshop'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_help_request'))
    )
    with op.batch_alter_table('help_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_help_request_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_request_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index('ix_help_request_workshop_status_created', ['workshop_id', 'status', 'created_at'], unique=False)

    op.create_table('milestone_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], name=op.f('fk_milestone_completion_milestone_id_milestone'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_milestone_completion_participant_id_participant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestone_completion')),
    sa.UniqueConstraint('participant_id', 'milestone_id', name='uq_completion_participant_milestone')
    )
    with op.batch_alter_table('milestone_completion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestone_completion_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestone_completion_participant_id'), ['participant_id'], unique=False)

    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('help_request_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['help_request_id'], ['help_request.id'], name=op.f('fk_ai_usage_help_request_id_help_request'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.id'], name=op.f('fk_ai_usage_workshop_id_workshop'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage'))
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_help_request_id'), ['help_request_id'], unique=False)
        batch_op.create_index('ix_ai_usage_workshop_created', ['workshop_id', 'created_at'], unique=False)

    op.create_table('help_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('help_request_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('answer_md', sa.Text(), nullable=False),
    sa.Column('draft', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('ai_model', sa.String(length=120), nullable=True),
    sa.Column('ai_context_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['help_request_id'], ['help_request.id'], name=op.f('fk_help_answer_help_request_id_help_request'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_help_answer'))
    )
    with op.batch_alter_table('help_answer', schema=None) as batch_op:
        batch_op.create_index('ix_help_answer_request_created', ['help_request_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help_answer', schema=None) as batch_op:
        batch_op.drop_index('ix_help_answer_request_created')

    op.drop_table('help_answer')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_usage_workshop_created')
        batch_op.drop_index(batch_op.f('ix_ai_usage_help_request_id'))

    op.drop_table('ai_usage')
    with op.batch_alter_table('milestone_completion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestone_completion_participant_id'))
        batch_op.drop_index(batch_op.f('ix_milestone_completion_milestone_id'))

    op.drop_table('milestone_completion')
    with op.batch_alter_table('help_request', schema=None) as batch_op:
        batch_op.drop_index('ix_help_request_workshop_status_created')
        batch_op.drop_index(batch_op.f('ix_help_request_participant_id'))
        batch_op.drop_index(batch_op.f('ix_help_request_milestone_id'))

    op.drop_table('help_request')
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participant_workshop_id'))
        batch_op.drop_index(batch_op.f('ix_participant_token'))

    op.drop_table('participant')
    with op.batch_alter_table('milestone', schema=None) as batch_op:
        batch_op.drop_index('ix_milestone_workshop_id_position')

    op.drop_table('milestone')
    with op.batch_alter_table('facilitator_action', schema=None) as batch_op:
        batch_op.drop_index('ix_facilitator_action_workshop_created')
        batch_op.drop_index(batch_op.f('ix_facilitator_action_created_at'))

    op.drop_table('facilitator_action')
    with op.batch_alter_table('broadcast', schema=None) as batch_op:
        batch_op.drop_index('ix_broadcast_workshop_cleared')

    op.drop_table('broadcast')
    with op.batch_alter_table('workshop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workshop_status'))
        batch_op.drop_index(batch_op.f('ix_workshop_join_slug'))
        batch_op.drop_index(batch_op.f('ix_workshop_cloned_from_id'))
        batch_op.drop_index(batch_op.f('ix_workshop_agenda_template_id'))
        batch_op.drop_index(batch_op.f('ix_workshop_admin_token'))

    op.drop_table('workshop')
    with op.batch_alter_table('agenda_template_milestone', schema=None) as batch_op:
        batch_op.drop_index('ix_agenda_template_milestone_template_position')

    op.drop_table('agenda_template_milestone')
    op.drop_table('join_form_template')
    op.drop_table('agenda_template')
    # ### end Alembic commands ###
